---
- name: ceph clients validation tests
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: get openstack's services client details
      shell: 'ceph auth get client.openstack --format json'
      become: true
      register: client_info
      run_once: yes
      tags:
        - clients
        - sanity
        - ceph-2

    - name: validate client permissions on pools
      include: tasks/check_client_permissions.yml variable='client_info'
      with_items: "{{ test.ceph.pools.split(',') }}"
      tags:
        - clients
        - sanity
        - ceph-2