---
- name: Check cluster status in a noncontainerized environment
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: collect Ceph cluster status
      shell: "ceph status --cluster {{test.cluster.name}} --format json"
      become: true
      register: cluster_status
      run_once: yes
      tags:
        - sanity
        - non-containerized
  # TODO: Add tasks for logging success/failure for noncontainerized health check (ceph2)

- name: Check cluster status in a containerized environment
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: collect Ceph cluster status
      shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph --cluster {{test.cluster.name}} --status --format json"
      become: true
      register: cluster_status
      run_once: yes
      tags:
        - sanity
        - containerized

    - name: cluster health check for ceph 3 - failed
      lineinfile:
        path: "{{ test.output.file }}"
        line: "check ceph monitors health = failed"
      when: ((cluster_status.stdout|from_json).health.status != "HEALTH_OK")
      delegate_to: undercloud-0
      run_once: yes
      tags:
        - cluster
        - sanity
        - ceph-3
    
    - name: cluster health check for ceph 3 - passed
      lineinfile:
        path: "{{ test.output.file }}"
        line: "check ceph monitors health = passed"
      when: ((cluster_status.stdout|from_json).health.status == "HEALTH_OK")
      delegate_to: undercloud-0
      run_once: yes
      tags:
        - cluster
        - sanity
        - ceph-3

    - name: cluster health check for ceph 4 - failed
      register: health_check
      lineinfile:
        path: "{{ test.output.file }}"
        line: "check ceph monitors health = failed"
      when: ((cluster_status.stdout|from_json).health.status != "HEALTH_OK")
      delegate_to: undercloud-0
      run_once: yes
      tags:
        - cluster
        - sanity
        - ceph-4

    - name: cluster health check for ceph 4 - passed
      register: health_check
      lineinfile:
        path: "{{ test.output.file }}"
        line: "check ceph monitors health = passed"
      when: ((cluster_status.stdout|from_json).health.status == "HEALTH_OK")
      delegate_to: undercloud-0
      run_once: yes
      tags:
        - cluster
        - sanity
        - ceph-4
