---
- name: Check cluster status
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: collect Ceph cluster status
      shell: "ceph status --format json"
      become: true
      register: cluster_status
      run_once: yes
      tags:
        - cluster
        - sanity

- name: Check cluster status in a containerized environment
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: collect Ceph cluster status
      shell: "docker exec ceph-mon-`hostname -s` ceph --status --forma json"
      become: true
      register: cluster_status
      run_once: yes
      tags:
        - cluster
        - sanity
        - containerized

    - name: Check cluster's health
      fail:
        msg: "The cluster is not healthy, the cluster status is: {{ (cluster_status.stdout|from_json).health.overall_status }}"
      when: ((cluster_status.stdout|from_json).health.overall_status == "HEALTH_ERR")
      run_once: yes
      tags:
        - cluster
        - sanity