---
- name: file content validation tests
  hosts: compute
  become: true
  tasks:
    - name: validate the default values of max_files & max_processes parameters in /etc/libvirt/qemu.conf (BZ#1372589)
      include: tasks/check_qemu_values.yml
      tags:
        - compute
        - file_contents

    - name: Validate ceph keyring permissions (BZ#1734513)
      include: tasks/check_keyring_permissions.yml
      tags:
        - compute
        - file_contents
        - containerized
