---
- name: validate ceph osds status
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: check OSDs were created - failed
      lineinfile:
        path: "{{ test.output.file }}"
        line: "Check OSD how much created = failed"
      when: (cluster_status.stdout|from_json).osdmap.osdmap.num_osds != {{ test.osds.number }}
      run_once: yes
      delegate_to: undercloud-0
      tags:
        - osds
        - sanity
      
    - name: check OSDs were created - passed
      lineinfile:
        path: "{{ test.output.file }}"
        line: "Check OSD how much created = passed"
      when: (cluster_status.stdout|from_json).osdmap.osdmap.num_osds == {{ test.osds.number }}
      run_once: yes
      delegate_to: undercloud-0
      tags:
        - osds
        - sanity

    - name: get osds list (ceph2)
      shell: "ceph --cluster {{test.cluster.name}} osd tree --format json"
      become: true
      register: osds_list
      run_once: yes
      tags:
        - osds
        - sanity
        - non-containerized

    - name: get osds list (ceph3)
      shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph --cluster {{test.cluster.name}} osd tree --format json"
      become: true
      register: osds_list
      run_once: yes
      tags:
        - osds
        - sanity
        - containerized
        - ceph-3

    - name: get osds list (ceph4)
      shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph --cluster {{test.cluster.name}} osd tree --format json"
      become: true
      register: osds_list
      run_once: yes
      tags:
        - osds
        - sanity
        - containerized
        - ceph-4

    - name: check osds status
      include: tasks/check_osds_status.yml
      with_items: '{{ (osds_list.stdout|from_json).nodes }}'
      run_once: yes
      tags:
        - osds
        - sanity
