---
- name: get pool's size (non-containerized)
  shell: "ceph osd pool get {{ item }} size --format json"
  become: true
  run_once: yes
  register: size
  tags:
    - non-containerized

- name: get pool's size (containerized)
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd pool get {{ item }} size --format json"
  become: true
  run_once: yes
  register: size
  tags:
    - containerized

- name: is size equal to value - failed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "check pool's size {{ item }} = failed"
  delegate_to: undercloud-0
  when: (size.stdout|from_json).size != {{ test.pool.size }}
  run_once: yes

<<<<<<< HEAD
- name: get pool's min_size (non-containerized)
=======
- name: is size equal to value - passed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "check pool's size {{ item }} = passed"
  delegate_to: undercloud-0
  when: (size.stdout|from_json).size == {{ test.pool.size }}
  run_once: yes

- name: get pool's min_size
>>>>>>> f0431e3... add jordan-results.out file and submitting results
  shell: "ceph osd pool get {{ item }} min_size --format json"
  become: true
  run_once: yes
  register: min_size
  tags:
    - non-containerized

- name: get pool's min_size (containerized)
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd pool get {{ item }} min_size --format json"
  become: true
  run_once: yes
  register: min_size
  tags:
    - containerized

- name: is min_size equal to value - failed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Set osd_pool_default_min_size automatically by Ceph {{ item }} = failed"
  when: (min_size.stdout|from_json).min_size != {{ test.pool.min_size }}
<<<<<<< HEAD
  run_once: yes
=======
  delegate_to: undercloud-0
  run_once: yes

- name: is min_size equal to value - passed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Set osd_pool_default_min_size automatically by Ceph {{ item }} = passed"
  when: (min_size.stdout|from_json).min_size == {{ test.pool.min_size }}
  delegate_to: undercloud-0
  run_once: yes
>>>>>>> f0431e3... add jordan-results.out file and submitting results
