---
- name: validate client read permissions on monitors - failed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Check ceph client permissions = failed"
  delegate_to: undercloud-0
  when: not (client_info.stdout|from_json)[0].caps.mon is search("allow r") or not (client_info.stdout|from_json)[0].caps.osd is search("allow rwx pool={{ item }}" )
  tags:
    - clients
    - sanity
    - ceph-2

- name: validate client read permissions on monitors - passed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Check ceph client permissions = passed"
  delegate_to: undercloud-0
  when: (client_info.stdout|from_json)[0].caps.mon is search("allow r") and (client_info.stdout|from_json)[0].caps.osd is search("allow rwx pool={{ item }}" )
  tags:
    - clients
    - sanity
    - ceph-2

- name: validate client read permissions on manager - failed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Check ceph client permissions = failed"
  delegate_to: undercloud-0
  when: not (client_info.stdout|from_json)[0].caps.mgr is search("allow *") or not (client_info.stdout|from_json)[0].caps.mon is search("profile rbd") or not (client_info.stdout|from_json)[0].caps.osd is search("profile rbd pool={{ item }}" )
  tags:
    - clients
    - sanity
    - ceph-3

- name: validate client read permissions on manager - passed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Check ceph client permissions = failed"
  delegate_to: undercloud-0
  when: (client_info.stdout|from_json)[0].caps.mgr is search("allow *") and (client_info.stdout|from_json)[0].caps.mon is search("profile rbd") and (client_info.stdout|from_json)[0].caps.osd is search("profile rbd pool={{ item }}" )
  tags:
    - clients
    - sanity
    - ceph-3

- name: validate client read permissions on manager - failed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Check ceph client permissions = failed"
  delegate_to: undercloud-0
  when: not (client_info.stdout|from_json)[0].caps.mgr is search("allow *") or not (client_info.stdout|from_json)[0].caps.mon is search("profile rbd") or not (client_info.stdout|from_json)[0].caps.osd is search("profile rbd pool={{ item }}" )
  tags:
    - clients
    - sanity
    - ceph-4

- name: validate client read permissions on manager - passed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Check ceph client permissions = passed"
  delegate_to: undercloud-0
  when: (client_info.stdout|from_json)[0].caps.mgr is search("allow *") and (client_info.stdout|from_json)[0].caps.mon is search("profile rbd") and (client_info.stdout|from_json)[0].caps.osd is search("profile rbd pool={{ item }}" )
  tags:
    - clients
    - sanity
    - ceph-4
