---
- name: get pool's size (non-containerized)
  shell: "ceph --cluster {{test.cluster.name}} osd pool get {{ item }} size --format json"
  become: true
  run_once: yes
  register: size
  tags:
    - non-containerized

- name: get pool's size (containerized)
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph --cluster {{test.cluster.name}} osd pool get {{ item }} size --format json"
  become: true
  run_once: yes
  register: size
  tags:
    - containerized

- name: is size equal to value - failed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "check pool's size {{ item }} = failed"
  delegate_to: undercloud-0
  when: (size.stdout|from_json).size != {{ test.pool.size }}

- name: is size equal to value - passed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "check pool's size {{ item }} = passed"
  delegate_to: undercloud-0
  when: (size.stdout|from_json).size != {{ test.pool.size }}

- name: get pool's min_size (non-containerized)
  shell: "ceph --cluster {{test.cluster.name}} osd pool get {{ item }} min_size --format json"
  become: true
  run_once: yes
  register: min_size
  tags:
    - non-containerized

- name: get pool's min_size (containerized)
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph --cluster {{test.cluster.name}} osd pool get {{ item }} min_size --format json"
  become: true
  run_once: yes
  register: min_size
  tags:
    - containerized

- name: is min_size equal to value - failed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Set osd_pool_default_min_size automatically by Ceph {{ item }} = failed"
  when: (min_size.stdout|from_json).min_size != {{ test.pool.min_size }}
  delegate_to: undercloud-0

- name: is min_size equal to value - passed
  lineinfile:
    path: "{{ test.output.file }}"
    line: "Set osd_pool_default_min_size automatically by Ceph {{ item }} = passed"
  when: (min_size.stdout|from_json).min_size != {{ test.pool.min_size }}
  delegate_to: undercloud-0
